### ISSUE TITLE
Error in e-static_profile.csh

### ISSUE THREAD

**Issue by rubyg0229** [ptools/ptools-legacy#48]
I am receiving errors when attempting to run this program. I am attempting to run this using the provided 1F1N_c_l.pdb file (which I have moved into the extra_scripts directory) on the command line such as below:
`./e-static_profile.csh 1FIN_c_l.pdb`

The first issue is encountered at the command:
`apbs ${name}.in > ${name}.out`

From this command I am receiving the errors:
`asc_getToken: Error occurred (bailing out).`
`Vio_scanf: Format problem with input.`

Then later in the script I receive the following output:
`[focusFillBound()]: WARNING:`
`Unusually large potential values`
`detected on the focusing boundary!`
`Convergence not guaranteed for NPBE/NRPBE calculations!`

`./e-static_profile.csh: line 195: syntax error: unexpected end of file`

I have reviewed the dependencies and believe all are installed. I have APBS version 1.4.1. Is this due to an error in the e-static_profile.csh script, the interaction with APBS, or any other potentially known issue. 

I think I should note that this script was found through installing ptools using from source, and that I also have a clone of the git repository which did not appear to include this specific script. Thank you for assistance with this issue.

**Comment by benoistlaurent** [comment]
I think you made an mistake posting this issue on PTools's issue tracker: e-static_profile.csh is not (and has never been) part of the PTools package.

**Comment by benoistlaurent** [comment]
Wrong post.

**Comment by rubyg0229** [comment]
If you download the source code tarball (ptools_2.0.tar.gz) from
https://sfiorucci.wordpress.com/downloads/ this produces a directory names
ptools_2.0_20150310. From this directory you can find e-static_profile.csh
in the directory
ptools_2.0_20150310/PyAttract/extra_scripts/e-static_prediction/ and there
is a script in this directory names e-static_profile.csh. As I pointed out
it is not a file included when you clone, but rather is only included if
you download the actual source code tarball.

**Comment by benoistlaurent** [comment]
OK thank you for the details.

I think the best chance you have to get an answer to your question is to contact directly S.Fiorruci as, again, I've not be able to find any trace of a file called `e-static_profile.csh` in the main git repository.

Thanks again for the feedback.

**Comment by charlestonchas** [comment]
Issue not currently relevant to the main PTools project, although it may be integrated in the future.
