### ISSUE TITLE
DNA: partitioning of the DNA backbone into residues in the dataBaseFile 

### ISSUE THREAD

**Issue by chantalprevost** [ptools/ptools-legacy#51]

**Comment by chantalprevost** [comment]
The partitioning was "Jumna-like" and not "Amber-like". Phosphates need to be transferred to adjacent residues. The attached files may do the job but there is a slight displacement in the base grains in the new file with respect to the old one;
2/ check continuity and compatibility with the Amber ordering after  constructing a given sequence

old files:   bp.ato.pdb.kp.txt   bp.red.pdb.kp.txt
new files: bp.ato.pdb.txt        bp.red.pdb.txt
(.txt : to be deletedafterwards, GitHub does not like .pdb)
[bp.ato.pdb.kp.txt](https://github.com/ptools/ptools/files/625080/bp.ato.pdb.kp.txt)
[bp.red.pdb.txt](https://github.com/ptools/ptools/files/625082/bp.red.pdb.txt)
[bp.red.pdb.kp.txt](https://github.com/ptools/ptools/files/625083/bp.red.pdb.kp.txt)
[bp.ato.pdb.txt](https://github.com/ptools/ptools/files/625071/bp.ato.pdb.txt)

**Comment by benoistlaurent** [comment]
@chantalprevost Chantal could you confirm this issue is solved, as the files you mention are now installed in `<prefix>/share/ptools`?

**Comment by chantalprevost** [comment]
Yes, I can. The issue is solved.
