### ISSUE TITLE
Install non-source files to <prefix>/share/ptools

### ISSUE THREAD

**Issue by benoistlaurent** [ptools/ptools-legacy#54]
Files such as `aminon.par` should be placed in the ptools repository under the directory 'data'.
They have to be installed in `<prefix>/share/ptools`.

**Comment by benboyer** [comment]
tentative list of files concerned:
currently in the ptools/PyAttract directory:

- aminon.par
- scorpion.par 
- mbest1u.par
- rotation.dat
- translation.dat
- attract.inp

the full content of ptools/PyAttract/reduce_data/

the basepairs PDB files in all Atom and Coarsegrain representation, not present yet and needed to use the DNA part of Ptools. (see issue #51)

**Comment by benoistlaurent** [comment]
Fixed by c4787999
