### ISSUE TITLE
DNA as submodule at the same level as Heligeom or PyAttract ?

### ISSUE THREAD

**Issue by chantalprevost** [ptools/ptools-legacy#58]
There are presently not many DNA python scripts (more exactly, 4 scripts) but these scripts are specific to DNA and they should be completed by other DNA scripts later.

**Comment by benoistlaurent** [comment]
As discussed in previous sprint, if there is not an obvious use of any script, a `ptools dna` command won't make sense.

Put those script in the upcoming `scripts` directory (as mentioned in #62)?

**Comment by chantalprevost** [comment]
I agree, the DNA scripts should be kept in the "scripts" directory
