### ISSUE TITLE
 MacOS v10.10, v10.12 Link error when compiling Tests/cpp/ptoolstest.bin during "make test"

### ISSUE THREAD

**Issue by charlestonchas** [ptools/ptools-legacy#66]
-- Error

    ld: can't link with bundle (MH_BUNDLE) only dylibs (MH_DYLIB) file '../../build/lib.macosx-10.10-x86_64-2.7/_ptools.so' for architecture x86_64

-- Problem: bundle, not dynamic library, is specified on MacOS, but dynamic library is needed.

-- Solution: Modify setup.py as suggested in http://stackoverflow.com/a/33105415

    if sys.platform == 'darwin':
        from distutils import sysconfig
        vars = sysconfig.get_config_vars()
        vars['LDSHARED'] = vars['LDSHARED'].replace('-bundle', '-dynamiclib')

**Comment by benoistlaurent** [comment]
Very nice.
I actually got the same error.

Are you going to modify the setup script or do you want me to do it?

**Comment by charlestonchas** [comment]
So it's pretty general for Mac. I'll let you make any changes, please?

**Comment by benoistlaurent** [comment]
OK

2016-12-13 11:25 GMT+01:00 charlestonchas <notifications@github.com>:

**Comment by charlestonchas** [comment]
I put this in setup.py in the macos-specific changes.
