### ISSUE TITLE
MacOS v10.10 Link error: missing symbols when linking cpp/ptoolstest.bin during "make test"

### ISSUE THREAD

**Issue by charlestonchas** [ptools/ptools-legacy#67]
-- Error

    ld: symbol(s) not found for architecture x86_64

-- Problem: Compilation of _ptools.so by "make build" defaults to the wrong libc++

-- Solution: Add "extra_compile_args" argument to setup.py to specify libstdc++, following http://stackoverflow.com/a/25080111

    ptools = Extension('_ptools',
                       sources=sources,
                       language='c++',
                       extra_compile_args=['-stdlib=libstdc++'],            <---- Add this
                       include_dirs=['headers'])

**Comment by benoistlaurent** [comment]
Have you tested it on both OS X and Linux?

**Comment by charlestonchas** [comment]
Sadly, it doesn't work for linux. Maybe we can somehow add it into the "darwin" section of setup.py from Issue #66 ? i'll look into it.

> (virtualpython-2.7.1)robert@alumini4:ptools$  docker start -ai ptools_interactive
> running build
> running build_py
> running build_ext
> Boost headers found at /usr/include
> f2c.h found at /usr/include
> libf2c.a found at /usr/lib/libf2c.a
> skipping 'bindings/_ptools.cpp' Cython extension (up-to-date)
> building '_ptools' extension
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Iheaders -I/usr/include/python2.7 -I/usr/include -I/usr/include -c src/BasePair.cpp -o build/temp.linux-x86_64-2.7/src/BasePair.o -stdlib=libstdc++
> x86_64-linux-gnu-gcc: error: unrecognized command line option '-stdlib=libstdc++'
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>

**Comment by charlestonchas** [comment]
Oops, I meant as in issue #66

**Comment by benoistlaurent** [comment]
We can totally do that.
I will do it ASAP.

**Comment by charlestonchas** [comment]
I added the cheese workaround to my macos-specific changes in setup.py.

**Comment by charlestonchas** [comment]
By specifying clang(++) for MacOS instead of g++, all works without this flag. Adding to setup.py.
