### ISSUE TITLE
Segmentation fault: 11 on Mac OSX

### ISSUE THREAD

**Issue by DomML** [ptools/ptools-legacy#73]
While trying to use the last version of ptools, I encounter this issue : 

"**********************************************************************
"**                                                                  **
"**                ATTRACT  (Python edition)                         **
"**                based on the PTools library                       **
"**                                                                  **
"**********************************************************************
PTools revision 615596a 2017-01-20 14:43:06 +0100

Start time: 2017-01-27 19:05:55.454700
Reading parameters file: attract.inp
7 series of minimizations
rstk =  0.0005
Reading receptor (fixed): 3G37.red with 23688 particules
Reading  ligand (mobile): R11-15_1_288.red with 2800 particules
Reading 214 translations from translation.dat
ntheta, nrot: 7 6
0.0 1
0.523598775 5
1.04719755 9
1.570796325 13
2.0943951 9
2.617993875 5
3.14159265 1
258 rotations by translation
"@@@@@@@ Translation nb 1 @@@@@@@
"----- Rotation nb 1 -----
{{ minimization nb 1 of 7 ; cutoff= 221.36 (A) ; maxiter= 10
number of free variables for the minimizer: 6
Segmentation fault: 11

thanks !

**Comment by benoistlaurent** [comment]
Could you give more details about the Python version and the OS you're
running.
Also it would be easier if you send the input files you used and the
command-line you ran.

Thanks

**Comment by DomML** [comment]
I use python 2.7 on Mac OSX 10.9

source /Users/dominique/Programs/ptools/env/bin/activate
~/Programs/ptools/PyAttract/attract.py -r 3G37.red -l R11-15_1_288.red -t 0
deactivate

[Archive.zip](https://github.com/ptools/ptools/files/738922/Archive.zip)

**Comment by benoistlaurent** [comment]
Thank you for the feedback.
We will look into this.

Be aware that we recently noticed that there are segmentation fault issues which are limited to OS X.
We are working on it.
In the mean time, I suggest you try on any Linux distribution if you can.

**Comment by DomML** [comment]
Indeed, it seems to work fine on Linux !
Thank you.

**Comment by benoistlaurent** [comment]
Just want to leave this issue open as it would be nice to have PTools working on OS X!

**Comment by DomML** [comment]
Ah, sorry.
I stay available if you need some Mac tester !

**Comment by benoistlaurent** [comment]
ok thanks!

**Comment by benoistlaurent** [comment]
@charlestonchas 

Nice: actually F2C stuff is also not working in Travis environment, which is Ubuntu 12.04 LTS:
https://travis-ci.org/ptools/ptools/builds/201448977

I therefore modified travis config so that tests are run on Ubuntu 14.04 LTS.

**Comment by benoistlaurent** [comment]
@charlestonchas: does the new procedure to compile Fortran solve this?
If so, problem solved!

**Comment by charlestonchas** [comment]
Yes! The no-f2c branch compiles and tests pass on macos Sierra using gcc6. I'll mention this in my pull request.

**Comment by charlestonchas** [comment]
Fixed by removing f2c dependency

**Comment by charlestonchas** [comment]
Fixed by removing f2c dependency. Now depends on gfortran to compile two fortran sources directly. Tested on Sierra 10.12.5 with gcc6 (ncludes gfortran) installed via macports.
