### ISSUE TITLE
ImportError: No module named Ptools

### ISSUE THREAD

**Issue by DomML** [ptools/ptools-legacy#74]
When trying to use translate.py, it raise 

  File "/home/z800/ptools/PyAttract/translate.py", line 17, in <module>
    from Ptools import (Rigidbody, Surface)
ImportError: No module named Ptools

It seems to be an upper case issue : when I change from "import Ptools" to "import ptools", it works.

**Comment by benoistlaurent** [comment]
Thank you for using PTools and providing some feedback.
You are totally right, ``import Ptools`` has to be replaced by ``import
ptools``.

**Teaser**
PTools team is currently working on a release that will hopefully be
available in the next months.

This release will contain heavy changes, making it easier to use the PTools
package, including library and scripts.
In this context, we are reviewing all the scripts available in the
distribution.
`translate.py` has already be rewrote and debugged.
Again, those changes will be integrated to the develop branch in the next
branch so please be patient, and excited about this new release!

Cheers
Ben

**Comment by benoistlaurent** [comment]
Thank you for using PTools and providing feedback.
You are totally right, `import Ptools` has to be replaced by `import ptools`.

**Teaser**
PTools team is currently working on a release that will hopefully be
available in the next months.

This release will contain heavy changes, making it easier to use the PTools
package, including library and scripts.
In this context, we are reviewing all the scripts available in the
distribution.
`translate.py` has already be rewrote and debugged.
Again, those changes will be integrated to the develop branch in the next
branch so please be patient, and excited about this new release!

Cheers
Ben

**Comment by charlestonchas** [comment]
This is no longer a problem in the **develop** branch.
